[versions]
kotlin = "2.1.0"
shadow = "8.3.5"
kotlinxCoroutines = "1.9.0"
sip = "1.3.0-91"

[libraries]
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
sip = { module = "javax.sip:jain-sip-ri", version.ref = "sip" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }